apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-rest-http
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-rest-http
    app.kubernetes.io/part-of: nodejs-rest-http
  name: nodejs-rest-http
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-rest-http
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-rest-http
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-engineering-rrus-tenant/nodejs-rest-http/nodejs-rest-http@sha256:f466bd7f287115423eae6cbd5102156f7122e7e4d0ddedb80853a26e9369bb7c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
