apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-rest-http
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-engineering-rrus-tenant/nodejs-rest-http/nodejs-rest-http@sha256:555f950bcced1e890337735ab8209a0146be7a81229f8549d9d6b79345746769
        name: my-nodejs
        resources: {}
status: {}
